In [23]:
import pandas as pd

In [24]:
dataset=pd.read_csv('/content/Training.csv')

In [25]:
dataset.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [26]:
dataset.shape

(4920, 133)

In [27]:
len(dataset['prognosis'].unique())

41

In [28]:
len(dataset['prognosis'].unique())

41

In [29]:
symptomes_dict={col: i for i,col in enumerate(dataset.columns)}

In [30]:
symptomes_dict

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelled_lymph_nodes': 47,
 'malaise': 48,
 'blurred_and_distorted_vision': 49,
 'phlegm': 50,
 'throat_irritation': 51,
 'redness_of_eyes': 52,
 'sinus_pressure': 53,
 'runny_nose': 54,
 'congestion': 55,
 'chest_pain': 56,
 'weakness_in_limbs': 57,
 'fast_heart_rate': 58,
 'pain_during_bowel_movements': 59,
 'pain_in_anal_region': 60,
 'bloody_stool': 61,
 'irritation_in_anus': 62,
 'neck_pain': 63,
 'dizziness': 64,
 'cramps': 65,
 'bruising': 66,
 'obesity': 67,
 'swollen_legs': 68,
 'swollen_blood_vessels': 69,
 'puffy_face_and_eyes': 70,
 'enlarged_thyroid': 71,
 'brittle_nails': 72,
 'swollen_extremeties': 73,
 'excessive_hunger': 74,
 'extra_marital_contacts': 75,
 'drying_and_tingling_lips': 76,
 'slurred_speech': 77,
 'knee_pain': 78,
 'hip_joint_pain': 79,
 'muscle_weakness': 80,
 'stiff_neck': 81,
 'swelling_joints': 82,
 'movement_stiffness': 83,
 'spinning_movements': 84,
 'loss_of_balance': 85,
 'unsteadiness': 86,
 'weakness_of_one_body_side': 87,
 'loss_of_smell': 88,
 'bladder_discomfort': 89,
 'foul_smell_of urine': 90,
 'continuous_feel_of_urine': 91,
 'passage_of_gases': 92,
 'internal_itching': 93,
 'toxic_look_(typhos)': 94,
 'depression': 95,
 'irritability': 96,
 'muscle_pain': 97,
 'altered_sensorium': 98,
 'red_spots_over_body': 99,
 'belly_pain': 100,
 'abnormal_menstruation': 101,
 'dischromic _patches': 102,
 'watering_from_eyes': 103,
 'increased_appetite': 104,
 'polyuria': 105,
 'family_history': 106,
 'mucoid_sputum': 107,
 'rusty_sputum': 108,
 'lack_of_concentration': 109,
 'visual_disturbances': 110,
 'receiving_blood_transfusion': 111,
 'receiving_unsterile_injections': 112,
 'coma': 113,
 'stomach_bleeding': 114,
 'distention_of_abdomen': 115,
 'history_of_alcohol_consumption': 116,
 'fluid_overload.1': 117,
 'blood_in_sputum': 118,
 'prominent_veins_on_calf': 119,
 'palpitations': 120,
 'painful_walking': 121,
 'pus_filled_pimples': 122,
 'blackheads': 123,
 'scurring': 124,
 'skin_peeling': 125,
 'silver_like_dusting': 126,
 'small_dents_in_nails': 127,
 'inflammatory_nails': 128,
 'blister': 129,
 'red_sore_around_nose': 130,
 'yellow_crust_ooze': 131,
 'prognosis': 132}

In [31]:
symptoms_dict={'itching': 0,'skin_rash': 1,'nodal_skin_eruptions': 2,'continuous_sneezing': 3,'shivering': 4,'chills': 5,'joint_pain': 6,'stomach_pain': 7,'acidity': 8, 'ulcers_on_tongue': 9,'muscle_wasting': 10,'vomiting': 11,'burning_micturition': 12,'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15,'anxiety': 16,'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22,'irregular_sugar_level': 23,'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27,'sweating': 28,'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37,'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54,'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58,'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63,'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72,'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75,'drying_and_tingling_lips': 76, 'slurred_speech': 77,'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96,'muscle_pain': 97,'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104,'polyuria': 105,'family_history': 106, 'mucoid_sputum': 107,'rusty_sputum': 108,'lack_of_concentration': 109,'visual_disturbances': 110,'receiving_blood_transfusion': 111,'receiving_unsterile_injections': 112,'coma': 113,'stomach_bleeding': 114,'distention_of_abdomen': 115,'history_of_alcohol_consumption': 116,'fluid_overload.1': 117,'blood_in_sputum': 118, 'prominent_veins_on_calf': 119,'palpitations': 120,'painful_walking': 121,'pus_filled_pimples': 122,'blackheads': 123,'scurring': 124,'skin_peeling': 125,'silver_like_dusting': 126,'small_dents_in_nails': 127,'inflammatory_nails': 128,'blister': 129,'red_sore_around_nose': 130,'yellow_crust_ooze': 131,'prognosis': 132}

In [32]:
dataset['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [33]:
unique_values=dataset['prognosis'].unique()

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [35]:
X=dataset.drop("prognosis",axis=1)
y=dataset['prognosis']

In [36]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [37]:
feature_columns=X.columns

In [38]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=20)

In [40]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

In [41]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [42]:
le=LabelEncoder()
le.fit(y)
Y=le.transform(y)

In [43]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [44]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [45]:
result_dict=dict(zip(map(int,Y),y))
print(result_dict)
diseases_list=result_dict

{15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

In [46]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np
 # create a dictonary to store models
models={
    "SVC":SVC(kernel='linear'),
    "RandomForest":RandomForestClassifier(n_estimators=100,random_state=42),
    "KNeighbors":KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB":MultinomialNB()
}
for model_name,model in models.items():
    #train model
    model.fit(X_train,y_train)
    #test model
    predictions=model.predict(X_test)
    #calculate accuracy
    accuracy=accuracy_score(y_test,predictions)

    #calculate confusion matrix
    cm=confusion_matrix(y_test,predictions)

    print(f"{model_name} accuracy:{accuracy}")
    print(f"{model_name} Confusin Matrix:")
    print(np.array2string(cm,separator=','))

SVC accuracy:1.0
SVC Confusin Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
RandomForest accuracy:1.0
RandomForest Confusin Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
KNeighbors accuracy:1.0
KNeighbors Confusin Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
MultinomialNB accuracy:1.0
MultinomialNB Confusin Matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]

In [47]:
svc=SVC(kernel='linear')
svc.fit(X_train,y_train)
ypred=svc.predict(X_test)
accuracy_score(y_test,ypred)

1.0

In [48]:
import pickle
import os

# Create the 'models' directory if it doesn't exist
os.makedirs('models', exist_ok=True)
pickle.dump(svc,open("models/svc.pkl",'wb'))

In [49]:
svc=pickle.load(open("models/svc.pkl",'rb'))

In [50]:
X_test

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
4037,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4191,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
432,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1266,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3765,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2327,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1906,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
#test 1
print("Predicted label:",svc.predict(X_test.iloc[[0]]))
print("Actual Label:",y_test.iloc[0])

Predicted label: ['hepatitis A']
Actual Label: hepatitis A

In [52]:
sym_des=pd.read_csv('/content/symtoms_df.csv')
precautions=pd.read_csv('/content/precautions_df.csv')
workout=pd.read_csv('/content/workout_df.csv') # Corrected file for workout data
description=pd.read_csv('/content/description.csv')
medications=pd.read_csv('/content/medications.csv')
diets=pd.read_csv('/content/diets.csv')

In [53]:
sym_des

,Unnamed: 0,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN
2,2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN
3,3,Fungal infection,itching,skin_rash,dischromic _patches,NaN
4,4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN
...,...,...,...,...,...,...
4915,4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements
4916,4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring
4917,4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine
4918,4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting
4919,4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose

In [54]:
precautions

,Unnamed: 0,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths
5,5,GERD,avoid fatty spicy food,avoid lying down after eating,maintain healthy weight,exercise
6,6,Chronic cholestasis,cold baths,anti itch medicine,consult doctor,eat healthy
7,7,hepatitis A,Consult nearest hospital,wash hands through,avoid fatty spicy food,medication
8,8,Osteoarthristis,acetaminophen,consult nearest hospital,follow up,salt baths
9,9,(vertigo) Paroymsal Positional Vertigo,lie down,avoid sudden change in body,avoid abrupt head movment,relax
10,10,Hypoglycemia,lie down on side,check in pulse,drink sugary drinks,consult doctor
11,11,Acne,bath twice,avoid fatty spicy food,drink plenty of water,avoid too many products
12,12,Diabetes,have balanced diet,exercise,consult doctor,follow up
13,13,Impetigo,soak affected area in warm water,use antibiotics,remove scabs with wet compressed cloth,consult doctor
14,14,Hypertension,meditation,salt baths,reduce stress,get proper sleep
15,15,Peptic ulcer diseae,avoid fatty spicy food,consume probiotic food,eliminate milk,limit alcohol
16,16,Dimorphic hemmorhoids(piles),avoid fatty spicy food,consume witch hazel,warm bath with epsom salt,consume alovera juice
17,17,Common Cold,drink vitamin c rich drinks,take vapour,avoid cold food,keep fever in check
18,18,Chicken pox,use neem in bathing,consume neem leaves,take vaccine,avoid public places
19,19,Cervical spondylosis,use heating pad or cold pack,exercise,take otc pain reliver,consult doctor
20,20,Hyperthyroidism,eat healthy,massage,use lemon balm,take radioactive iodine treatment
21,21,Urinary tract infection,drink plenty of water,increase vitamin c intake,drink cranberry juice,take probiotics
22,22,Varicose veins,lie down flat and raise the leg high,use oinments,use vein compression,dont stand still for long
23,23,AIDS,avoid open cuts,wear ppe if possible,consult doctor,follow up
24,24,Paralysis (brain hemorrhage),massage,eat healthy,exercise,consult doctor
25,25,Typhoid,eat high calorie vegitables,antiboitic therapy,consult doctor,medication
26,26,Hepatitis B,consult nearest hospital,vaccination,eat healthy,medication
27,27,Fungal infection,bath twice,use detol or neem in bathing water,keep infected area dry,use clean cloths
28,28,Hepatitis C,Consult nearest hospital,vaccination,eat healthy,medication
29,29,Migraine,meditation,reduce stress,use poloroid glasses in sun,consult doctor
30,30,Bronchial Asthma,switch to loose cloothing,take deep breaths,get away from trigger,seek help
31,31,Alcoholic hepatitis,stop alcohol consumption,consult doctor,medication,follow up
32,32,Jaundice,drink plenty of water,consume milk thistle,eat fruits and high fiberous food,medication
33,33,Hepatitis E,stop alcohol consumption,rest,consult doctor,medication
34,34,Dengue,drink papaya leaf juice,avoid fatty spicy food,keep mosquitos away,keep hydrated
35,35,Hepatitis D,consult doctor,medication,eat healthy,follow up
36,36,Heart attack,call ambulance,chew or swallow asprin,keep calm,NaN
37,37,Pneumonia,consult doctor,medication,rest,follow up
38,38,Arthritis,exercise,use hot and cold therapy,try acupuncture,massage
39,39,Gastroenteritis,stop eating solid food for while,try taking small sips of water,rest,ease back into eating
40,40,Tuberculosis,cover mouth,consult doctor,medication,rest

In [55]:
workout

,Unnamed: 0.1,Unnamed: 0,disease,workout
0,0,0,Fungal infection,Avoid sugary foods
1,1,1,Fungal infection,Consume probiotics
2,2,2,Fungal infection,Increase intake of garlic
3,3,3,Fungal infection,Include yogurt in diet
4,4,4,Fungal infection,Limit processed foods
...,...,...,...,...
405,405,405,Impetigo,Consult a healthcare professional
406,406,406,Impetigo,Follow medical recommendations
407,407,407,Impetigo,Avoid scratching
408,408,408,Impetigo,Take prescribed antibiotics
409,409,409,Impetigo,Practice wound care

In [56]:
description

,Disease,Description
0,Fungal infection,Fungal infection is a common skin condition ca...
1,Allergy,Allergy is an immune system reaction to a subs...
2,GERD,GERD (Gastroesophageal Reflux Disease) is a di...
3,Chronic cholestasis,Chronic cholestasis is a condition where bile ...
4,Drug Reaction,Drug Reaction occurs when the body reacts adve...
5,Peptic ulcer disease,Peptic ulcer disease involves sores that devel...
6,AIDS,AIDS (Acquired Immunodeficiency Syndrome) is a...
7,Diabetes,Diabetes is a chronic condition that affects h...
8,Gastroenteritis,Gastroenteritis is an inflammation of the stom...
9,Bronchial Asthma,Bronchial Asthma is a respiratory condition ch...
10,Hypertension,"Hypertension, or high blood pressure, is a com..."
11,Migraine,Migraine is a type of headache that often invo...
12,Cervical spondylosis,Cervical spondylosis is a degenerative conditi...
13,Paralysis (brain hemorrhage),Paralysis (brain hemorrhage) refers to the los...
14,Jaundice,Jaundice is a yellow discoloration of the skin...
15,Malaria,Malaria is a mosquito-borne infectious disease...
16,Chicken pox,Chicken pox is a highly contagious viral infec...
17,Dengue,Dengue is a mosquito-borne viral infection cau...
18,Typhoid,Typhoid is a bacterial infection that can lead...
19,hepatitis A,hepatitis A is a viral liver disease.
20,Hepatitis B,Hepatitis B is a viral infection that attacks ...
21,Hepatitis C,Hepatitis C is a viral infection that causes l...
22,Hepatitis D,Hepatitis D is a serious liver disease caused ...
23,Hepatitis E,Hepatitis E is a viral infection that causes l...
24,Alcoholic hepatitis,Alcoholic hepatitis is inflammation of the liv...
25,Tuberculosis,Tuberculosis is a bacterial infection that pri...
26,Common Cold,Common Cold is a viral infection of the upper ...
27,Pneumonia,Pneumonia is an inflammatory condition affecti...
28,Dimorphic hemmorhoids(piles),Dimorphic hemmorhoids(piles) is a condition ch...
29,Heart attack,Heart attack is a sudden and severe reduction ...
30,Varicose veins,"Varicose veins are enlarged, twisted veins tha..."
31,Hypothyroidism,Hypothyroidism is a condition where the thyroi...
32,Hyperthyroidism,Hyperthyroidism is a condition where the thyro...
33,Hypoglycemia,Hypoglycemia is a condition characterized by a...
34,Osteoarthristis,Osteoarthristis is a degenerative joint diseas...
35,Arthritis,Arthritis is inflammation of one or more joint...
36,(vertigo) Paroymsal Positional Vertigo,(Vertigo) Paroxysmal Positional Vertigo is a t...
37,Acne,Acne is a skin condition that occurs when hair...
38,Urinary tract infection,Urinary tract infection is an infection in any...
39,Psoriasis,Psoriasis is a chronic skin condition characte...
40,Impetigo,Impetigo is a highly contagious skin infection...

In [57]:
medications

,Disease,Medication
0,Fungal infection,"['Antifungal Cream', 'Fluconazole', 'Terbinafi..."
1,Allergy,"['Antihistamines', 'Decongestants', 'Epinephri..."
2,GERD,"['Proton Pump Inhibitors (PPIs)', 'H2 Blockers..."
3,Chronic cholestasis,"['Ursodeoxycholic acid', 'Cholestyramine', 'Me..."
4,Drug Reaction,"['Antihistamines', 'Epinephrine', 'Corticoster..."
5,Peptic ulcer disease,"['Antibiotics', 'Proton Pump Inhibitors (PPIs)..."
6,AIDS,"['Antiretroviral drugs', 'Protease inhibitors'..."
7,Diabetes,"['Insulin', 'Metformin', 'Sulfonylureas', 'DPP..."
8,Gastroenteritis,"['Antibiotics', 'Antiemetic drugs', 'Antidiarr..."
9,Bronchial Asthma,"['Bronchodilators', 'Inhaled corticosteroids',..."
10,Hypertension,"['Antihypertensive medications', 'Diuretics', ..."
11,Migraine,"['Analgesics', 'Triptans', 'Ergotamine derivat..."
12,Cervical spondylosis,"['Pain relievers', 'Muscle relaxants', 'Physic..."
13,Paralysis (brain hemorrhage),"['Blood thinners', 'Clot-dissolving medication..."
14,Jaundice,"['IV fluids', 'Blood transfusions', 'Liver tra..."
15,Malaria,"['Antimalarial drugs', 'Antipyretics', 'Antiem..."
16,Chicken pox,"['Antiviral drugs', 'Pain relievers', 'IV flui..."
17,Dengue,"['Antibiotics', 'Antipyretics', 'Analgesics', ..."
18,Typhoid,"['Vaccination', 'Antiviral drugs', 'IV fluids'..."
19,hepatitis A,"['Vaccination', 'Antiviral drugs', 'IV fluids'..."
20,Hepatitis B,"['Antiviral drugs', 'IV fluids', 'Blood transf..."
21,Hepatitis C,"['Antiviral drugs', 'IV fluids', 'Blood transf..."
22,Hepatitis D,"['Antiviral drugs', 'IV fluids', 'Blood transf..."
23,Hepatitis E,"['Alcohol cessation', 'Corticosteroids', 'IV f..."
24,Alcoholic hepatitis,"['Antibiotics', 'Isoniazid', 'Rifampin', 'Etha..."
25,Tuberculosis,"['Antipyretics', 'Decongestants', 'Cough suppr..."
26,Common Cold,"['Antibiotics', 'Antiviral drugs', 'Antifungal..."
27,Pneumonia,"['Laxatives', 'Pain relievers', 'Warm baths', ..."
28,Dimorphic hemmorhoids(piles),"['Nitroglycerin', 'Aspirin', 'Beta-blockers', ..."
29,Heart attack,"['Compression stockings', 'Exercise', 'Elevati..."
30,Varicose veins,"['Levothyroxine', 'Antithyroid medications', '..."
31,Hypothyroidism,"['Antithyroid medications', 'Radioactive iodin..."
32,Hyperthyroidism,"['Glucose tablets', 'Candy or juice', 'Glucago..."
33,Hypoglycemia,"['Pain relievers', 'Exercise', 'Hot and cold p..."
34,Osteoarthristis,"['NSAIDs', 'Disease-modifying antirheumatic dr..."
35,Arthritis,"['Vestibular rehabilitation', 'Canalith reposi..."
36,(vertigo) Paroymsal Positional Vertigo,"['Topical treatments', 'Antibiotics', 'Oral me..."
37,Acne,"['Antibiotics', 'Pain relievers', 'Antihistami..."
38,Urinary tract infection,"['Antibiotics', 'Urinary analgesics', 'Phenazo..."
39,Psoriasis,"['Topical treatments', 'Phototherapy', 'System..."
40,Impetigo,"['Topical antibiotics', 'Oral antibiotics', 'A..."

In [58]:
print(diseases_list)

{15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

In [59]:
symptoms_dict={'itching': 0,'skin_rash': 1,'nodal_skin_eruptions': 2,'continuous_sneezing': 3,'shivering': 4,'chills': 5,'joint_pain': 6,'stomach_pain': 7,'acidity': 8, 'ulcers_on_tongue': 9,'muscle_wasting': 10,'vomiting': 11,'burning_micturition': 12,'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15,'anxiety': 16,'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22,'irregular_sugar_level': 23,'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27,'sweating': 28,'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37,'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54,'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58,'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63,'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72,'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75,'drying_and_tingling_lips': 76, 'slurred_speech': 77,'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96,'muscle_pain': 97,'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104,'polyuria': 105,'family_history': 106, 'mucoid_sputum': 107,'rusty_sputum': 108,'lack_of_concentration': 109,'visual_disturbances': 110,'receiving_blood_transfusion': 111,'receiving_unsterile_injections': 112,'coma': 113,'stomach_bleeding': 114,'distention_of_abdomen': 115,'history_of_alcohol_consumption': 116,'fluid_overload.1': 117,'blood_in_sputum': 118, 'prominent_veins_on_calf': 119,'palpitations': 120,'painful_walking': 121,'pus_filled_pimples': 122,'blackheads': 123,'scurring': 124,'skin_peeling': 125,'silver_like_dusting': 126,'small_dents_in_nails': 127,'inflammatory_nails': 128,'blister': 129,'red_sore_around_nose': 130,'yellow_crust_ooze': 131,'prognosis': 132}
# model prediction function
#def get_predicted_value(patient_symptoms):
       #input_vector=np.zeros(len(symptoms_dict))
       #for item in patient_symptoms:
           #input_vector[symptoms_dict[item]]=1
           #input_df=pd.DataFrame([input_vector],columns=symptoms_dict.keys())
          # return diseases_list[svc.predict(input_df)[0]]
def helper(dis):
    desc=description[description['Disease']==dis]['Description']
    desc=" ".join([w for w in desc.values])

    pre=precautions[precautions['Disease']==dis][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']]
    pre=[col for col in pre.values]

    med=medications[medications['Disease']==dis]['Medication']
    med=[med for med in med.values]

    die=diets[diets['Disease']==dis]['Diet']
    die=[die for die in die.values]

    wrkout=workout[workout['disease']==dis]['workout'] # Corrected to 'disease' and 'workout'

    return desc,pre,med,die,wrkout
def get_predicted_value(patient_symptoms):

    input_vector = [0] * len(feature_columns)

    for item in patient_symptoms:
        if item in symptoms_dict:
            input_vector[symptoms_dict[item]] = 1

    input_df = pd.DataFrame([input_vector], columns=feature_columns)

    prediction = svc.predict(input_df)[0]

    return prediction

In [61]:
#test1
symptoms=input("Enter your symptoms....")
symptoms
user_symptoms=[s.strip() for s in symptoms.split(',')]
user_symptoms=[sym.strip("[] '") for sym  in user_symptoms]
predicted_disease=get_predicted_value(user_symptoms)
desc,pre,med,die,wrkout=helper(predicted_disease)
 # results
print(" -------   Predicted Disease ------ ")
print(predicted_disease)
print(" ----------  Description -----------")
print(desc)
print("------------- Precaution -----------")
i=1
for p_i in pre[0]:
    print(i,":",p_i)
    i+=1
print("------------- Medication -----------")
i=1
for m_i in med:
    print(i,":",m_i)
    i+=1
print("------------ Workout -----------")
i=1
for w_i in wrkout:
    print(i,":",w_i)
    i+=1

print("------------ Diet -----------")
i=1
for d in die:
    print(i,":",d)
    i+=1

Enter your symptoms....itching,skin_rash
 -------   Predicted Disease ------
Fungal infection
 ----------  Description -----------
Fungal infection is a common skin condition caused by fungi.
------------- Precaution -----------
1 : bath twice
2 : use detol or neem in bathing water
3 : keep infected area dry
4 : use clean cloths
------------- Medication -----------
1 : ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
------------ Workout -----------
1 : Avoid sugary foods
2 : Consume probiotics
3 : Increase intake of garlic
4 : Include yogurt in diet
5 : Limit processed foods
6 : Stay hydrated
7 : Consume green tea
8 : Eat foods rich in zinc
9 : Include turmeric in diet
10 : Eat fruits and vegetables
------------ Diet -----------
1 : ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

In [ ]:
_